
export const ActionTypes = {
	SET_PRODUCTS : 'SET_PRODUCTS',
	SELECTED_PRODUCT : 'SELECTED_PRODUCT',
	REMOVE_SELECTED_PRODUCTS : 'REMOVE_SELECTED_PRODUCTS',
	GETCARTITEM : 'GETCARTITEM',
	ADDITEM :'ADDITEM',
	INCREASEITEM :'INCREASEITEM',
	REMOVEITEM: 'REMOVEITEM',
	DECREASEITEM:'DECREASEITEM'
}

